// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoUnlockSSH(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AutoUnlockSSH'](arg1, arg2, arg3, arg4, arg5);
}

export function BackupRouter(arg1, arg2) {
  return window['go']['main']['App']['BackupRouter'](arg1, arg2);
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function ClearWorkflowState() {
  return window['go']['main']['App']['ClearWorkflowState']();
}

export function FlashUBoot(arg1) {
  return window['go']['main']['App']['FlashUBoot'](arg1);
}

export function GetAdapters() {
  return window['go']['main']['App']['GetAdapters']();
}

export function GetDefaultPaths(arg1) {
  return window['go']['main']['App']['GetDefaultPaths'](arg1);
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function InspectMaterials(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InspectMaterials'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InspectRouter(arg1) {
  return window['go']['main']['App']['InspectRouter'](arg1);
}

export function LaunchUnlockTool(arg1) {
  return window['go']['main']['App']['LaunchUnlockTool'](arg1);
}

export function LoadWorkflowState() {
  return window['go']['main']['App']['LoadWorkflowState']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ProbeWeb(arg1) {
  return window['go']['main']['App']['ProbeWeb'](arg1);
}

export function SaveWorkflowState(arg1) {
  return window['go']['main']['App']['SaveWorkflowState'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SetDHCP(arg1) {
  return window['go']['main']['App']['SetDHCP'](arg1);
}

export function SetOpenWrtIP(arg1, arg2) {
  return window['go']['main']['App']['SetOpenWrtIP'](arg1, arg2);
}

export function SetStaticIP(arg1, arg2) {
  return window['go']['main']['App']['SetStaticIP'](arg1, arg2);
}

export function TakeAutoRunModel() {
  return window['go']['main']['App']['TakeAutoRunModel']();
}

export function TakeAutoRunPassword() {
  return window['go']['main']['App']['TakeAutoRunPassword']();
}

export function WaitForOpenWrt(arg1) {
  return window['go']['main']['App']['WaitForOpenWrt'](arg1);
}

export function WaitForUBoot(arg1) {
  return window['go']['main']['App']['WaitForUBoot'](arg1);
}
