// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {flasher} from '../models';
import {main} from '../models';

export function AutoUnlockSSH(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<flasher.RouterInfo>;

export function BackupRouter(arg1:flasher.SSHConfig,arg2:string):Promise<flasher.BackupResult>;

export function Cancel():Promise<void>;

export function ClearWorkflowState():Promise<void>;

export function FlashUBoot(arg1:flasher.FlashInput):Promise<flasher.FlashResult>;

export function GetAdapters():Promise<Array<main.Adapter>>;

export function GetDefaultPaths(arg1:string):Promise<main.DefaultPaths>;

export function GetLogPath():Promise<string>;

export function InspectMaterials(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<flasher.Materials>;

export function InspectRouter(arg1:flasher.SSHConfig):Promise<flasher.RouterInfo>;

export function LaunchUnlockTool(arg1:string):Promise<void>;

export function LoadWorkflowState():Promise<main.WorkflowState>;

export function OpenURL(arg1:string):Promise<void>;

export function ProbeWeb(arg1:string):Promise<flasher.ProbeResult>;

export function SaveWorkflowState(arg1:main.WorkflowState):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:Array<string>):Promise<string>;

export function SetDHCP(arg1:string):Promise<void>;

export function SetOpenWrtIP(arg1:string,arg2:string):Promise<void>;

export function SetStaticIP(arg1:string,arg2:string):Promise<void>;

export function TakeAutoRunModel():Promise<string>;

export function TakeAutoRunPassword():Promise<string>;

export function WaitForOpenWrt(arg1:string):Promise<flasher.ProbeResult>;

export function WaitForUBoot(arg1:string):Promise<flasher.ProbeResult>;
